### ISSUE TITLE
Recommended way to use drizzle to access data in two steps?

### ISSUE THREAD

**Issue by camipe** [trufflesuite/drizzle-react#26]
Hello,

I've been pulling my hair for the last week and as I don't have any left now I figured I must ask for help.

I have a contract keeping track of a bunch of "goal-structs" stored in a public array, to retrieve a user's goal in the client I have created a function called `getGoalsByOwner` which returns an array of indexes of goals where the current user is owner of. To retrieve the goals I then loop over the index array and call the public getter for the goals array with each index (this is using the normal web3 calls, not cacheCalls).

How would you recommend I implement drizzle for this?
I've been trying to first get the indexes by a normal web3 call as they return a promise and then I get the goals using the indexes and drizzle's cacheCall flow, haven't really gotten it to work yet but is this a good way to go about it? Will Drizzle automatically re-render with the latest indexes if I add a goal to the array this way?

Also, a lot of the times my app crashes and get stuck on "loading dapp..." when I try things out in the render function. All I get is a long long error message starting with `uncaught at initializeDrizzle render@http://localhost:3000/static/js/bundle.js:105725:12`.
Is this supposed to happen? It makes it kind of hard to troubleshoot what I did wrong since the error is not very descriptive.

Hope someone can help me out :)

**Comment by adrianmcli** [comment]
Since you're getting the indexes via a raw web3.js call, the indexes will probably not update unless you explicitly tell it to. You can do this by passing in a callback function down to your child components. It'll essentially trigger a call to get the new indexes and an eventual re-render of the tree.

As for your error, I'm really not too sure what is going on. At any rate, I'm going to close this issue for now as it has been a couple of months. Can re-open if others have the same issue.
