### ISSUE TITLE
Is this repo (or drizzle-react-components for that matter) still maintained?

### ISSUE THREAD

**Issue by remon-nashid** [trufflesuite/drizzle-react#48]

**Comment by Garoth** [comment]
I'm not a drizzle dev, but I wanted to say that the project *does* work, although development has slowed. I know the Truffle team has just released a massive new version (v5) that overhauls a lot of their tech -- probably this is the reason that Drizzle development has slowed.

Anyway, yeah, it's a pain in the ass to go through all the docs and understand how you're supposed to use it. Some of the docs are outdated, because the Drizzle guys realized that their systems should use the new React Context APIs instead of the legacy redux stuff. A lot of the demo code still uses the legacy APIs (which do also work, but have more quirks I think)

But Drizzle does work overall (with a few shortcomings), and I use it in my production site, https://flowerpatch.app

**Comment by remon-nashid** [comment]
Thank you @Garoth. I realise that Drizze works, albeit with many code changes that need to be applied. That's quite manifested in the large number of forks to these repos. Also there's a dozen useful PRs that can tackle existing issues but not one is catering to them.

I think drizzle ecosystem is extremely useful and I've learned a lot from it. Hence, I really hope that it's not abandoned.

**Comment by kombos** [comment]
@Garoth  did you use DrizzleContext.Provider & DrizzleContext.Consumer in your app  ? is it working properly or is it re-rendering infinitely? please check this issue: 
https://github.com/trufflesuite/drizzle-react/issues/51

**Comment by adrianmcli** [comment]
There's a lot we are working on, but yes we are still trying to maintain this repo. Sorry for the late reply, most of us were on holidays when this issue was made and we missed it. Sorry about that.

But to answer the question, yes, we are still trying to maintain this.

**Comment by adrianmcli** [comment]
@Garoth We are trying to move to the new Context API, but it's difficult doing that in Drizzle-React-Components without deprecating the old stuff. The thing is, we need to keep supporting people who are pre-v16.3 React, so we are trying to support both APIs and it's quite difficult to do that across: `drizzle-react`, `drizzle-react-components`, and `drizzle-box`.

**Comment by adrianmcli** [comment]
@remon-nashid Feel free to tag me personally at some of the PRs that you feel need special attention. Right now, we are still swamped with issue triage.

This shouldn't be an excuse, but do note that we have been doing a lot of work in non-Drizzle repos. Personally, I have re-written the React/Webpack/Drizzle boxes from scratch in recent months.

**Comment by adrianmcli** [comment]
I'm closing this for now, since I have answered the question. But feel free to keep the discussion going. And feel free to tag me if you don't get any replies for a while.
